import { Boat, Review } from './types';

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    boatId: 'boat-1',
    reviewerName: 'Aarav Sharma',
    cleanliness: 5,
    punctuality: 4,
    safety: 5,
    overall: 5,
    comment: 'Captain Verma was amazing! Water was up to my thighs in Connaught Place, but he arrived with dry towels and warm samosas. True hero of the CP Basin.',
    createdAt: '2026-07-08T12:00:00Z'
  },
  {
    id: 'rev-2',
    boatId: 'boat-1',
    reviewerName: 'Priya Patel',
    cleanliness: 4,
    punctuality: 5,
    safety: 4,
    overall: 4.5,
    comment: 'Super fast arrival. Commute was literally zero traffic because roads were closed to cars but open for canoes! Paddled right over a stranded SUV.',
    createdAt: '2026-07-09T09:30:00Z'
  },
  {
    id: 'rev-3',
    boatId: 'boat-2',
    reviewerName: 'Rohit Singh',
    cleanliness: 5,
    punctuality: 5,
    safety: 5,
    overall: 5,
    comment: 'The Monsooner is basically a floating sofa. Highly recommended for executive flood evacuation. The noise of the Yamaha motor drowned out my existential dread.',
    createdAt: '2026-07-07T18:45:00Z'
  },
  {
    id: 'rev-4',
    boatId: 'boat-3',
    reviewerName: 'Meera Iyer',
    cleanliness: 4,
    punctuality: 4,
    safety: 5,
    overall: 4.5,
    comment: 'A bit slow because it is a paddle boat, but Captain Rajesh has great upper body strength and kept singing old Bollywood songs which kept our spirits high!',
    createdAt: '2026-07-09T14:15:00Z'
  },
  {
    id: 'rev-5',
    boatId: 'boat-2',
    reviewerName: 'Kabir Mehta',
    cleanliness: 5,
    punctuality: 5,
    safety: 4,
    overall: 5,
    comment: 'My Uber cancelled 4 times near Noida Sector 62. Called Captain Singh—he arrived in a sleek speedboat and zipped me directly to my office balcony. Incredible!',
    createdAt: '2026-07-09T11:20:00Z'
  },
  {
    id: 'rev-6',
    boatId: 'boat-4',
    reviewerName: 'Sunita Rao',
    cleanliness: 4,
    punctuality: 5,
    safety: 5,
    overall: 5,
    comment: 'Activated SOS when CP turned into a lake. Captain Rajesh arrived within 3 minutes on his heavy-duty raft. Saved my laptop and my sanity!',
    createdAt: '2026-07-09T17:10:00Z'
  },
  {
    id: 'rev-7',
    boatId: 'boat-5',
    reviewerName: 'Devansh Goel',
    cleanliness: 3,
    punctuality: 4,
    safety: 3,
    overall: 4.0,
    comment: 'Used the Sinking Feeling Solo Kayak to reach my quarterly business review. Had to help paddle for 10 minutes, but reached 100% dry. Best cardio session ever.',
    createdAt: '2026-07-10T08:05:00Z'
  }
];

export const INITIAL_BOATS: Boat[] = [
  {
    id: 'boat-1',
    name: 'Majestic Monsoon Canoe 3000',
    ownerId: 'owner-verma',
    ownerName: 'Captain Verma',
    type: 'canoe',
    capacity: 3,
    pricePerHour: 450,
    rating: 4.8,
    reviewsCount: 12,
    distanceKm: 0.8,
    nextAvailableTime: 'Within 5 minutes',
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&q=80&w=600',
    description: 'A premium hand-crafted wooden canoe engineered specifically for urban watercourses, pothole-dodging, and heavy street currents. Captain Verma has over 15 years of experience paddling through Delhi waterlogs. Comes with double-varnished cedarwood paddles.',
    isCovered: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
    operatingArea: 'Connaught Place & Lajpat Nagar',
    safetyEquipment: ['Premium Life Jackets', 'Water Horn', 'Inflatable Samosa Holder', 'Umbrella', 'Emergency Tea Flask'],
    blockedDates: ['2026-07-15'],
    coordinates: { x: 38, y: 45 },
    captainName: 'Captain Verma',
    captainRating: 4.9,
    captainAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    status: 'active'
  },
  {
    id: 'boat-2',
    name: 'The Hydro-Glide Speedster',
    ownerId: 'owner-singh',
    ownerName: 'Captain Singh',
    type: 'motorboat',
    capacity: 6,
    pricePerHour: 1200,
    rating: 4.9,
    reviewsCount: 34,
    distanceKm: 1.4,
    nextAvailableTime: 'Immediate Splash',
    imageUrl: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&q=80&w=600',
    description: 'Fitted with a 40hp quiet Yamaha outboard motor. Literally zips over submerged scooters, floating tires, and flooded service lanes. Complete with a clear vinyl canopy to protect passengers from monsoon deluges.',
    isCovered: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
    operatingArea: 'Sector 62, Noida & Indirapuram',
    safetyEquipment: ['6x High-Buoyancy Jackets', 'First Aid Floating Kit', 'Heavy Duty Tow Rope', 'Emergency Flare Gun', 'Samosa Warmer Chamber'],
    blockedDates: [],
    coordinates: { x: 55, y: 32 },
    captainName: 'Captain Singh',
    captainRating: 4.8,
    captainAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
    status: 'active'
  },
  {
    id: 'boat-3',
    name: 'Sunderbans Shikara Cruiser',
    ownerId: 'owner-mukherjee',
    ownerName: 'Captain Mukherjee',
    type: 'shikara',
    capacity: 4,
    pricePerHour: 600,
    rating: 4.6,
    reviewsCount: 8,
    distanceKm: 2.1,
    nextAvailableTime: 'In 12 minutes',
    imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&q=80&w=600',
    description: 'An elegant Dal-lake style luxury shikara decorated with traditional silk drapes. Best for romantic flood-evacuations, premium office commutes, or highly instagrammable waterlogging content. Cushions are fully water-resistant.',
    isCovered: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    operatingArea: 'South Extension & Green Park',
    safetyEquipment: ['4x Silk-Trimmed Life Vests', 'Sound system', 'Hot Chai Thermos', 'Comfort Pillows'],
    blockedDates: ['2026-07-12'],
    coordinates: { x: 62, y: 58 },
    captainName: 'Captain Mukherjee',
    captainRating: 4.7,
    captainAvatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150',
    status: 'active'
  },
  {
    id: 'boat-4',
    name: 'Yellow Submarine Raft (SOS Certified)',
    ownerId: 'owner-rajesh',
    ownerName: 'Captain Rajesh',
    type: 'raft',
    capacity: 8,
    pricePerHour: 350,
    rating: 4.4,
    reviewsCount: 19,
    distanceKm: 0.5,
    nextAvailableTime: 'In 3 minutes',
    imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&q=80&w=600',
    description: 'A heavy-duty military-grade inflatable white-water raft. Unsinkable, bounceable, and highly resilient to floating street poles or submerged divider curbs. Captain Rajesh handles it like a wild bull and loves playing high-energy music.',
    isCovered: false,
    isPetFriendly: true,
    isWheelchairAccessible: true,
    operatingArea: 'South Delhi & Greater Kailash',
    safetyEquipment: ['8x Professional Helmets', '8x Buoyancy Aids', 'Foot Pump', 'Karaoke Mic', 'Watertight Phone Pouches'],
    blockedDates: [],
    coordinates: { x: 42, y: 52 },
    captainName: 'Captain Rajesh',
    captainRating: 4.5,
    captainAvatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=150',
    status: 'active'
  },
  {
    id: 'boat-5',
    name: 'Sinking Feeling Solo Kayak',
    ownerId: 'owner-verma',
    ownerName: 'Captain Verma',
    type: 'kayak',
    capacity: 1,
    pricePerHour: 200,
    rating: 4.5,
    reviewsCount: 6,
    distanceKm: 3.2,
    nextAvailableTime: 'In 20 minutes',
    imageUrl: 'https://images.unsplash.com/photo-1517176118179-c554e7686550?auto=format&fit=crop&q=80&w=600',
    description: 'Perfect for lone-wolf corporate employees who need to reach an urgent stand-up meeting. High-performance fiberglass kayak. Note: You must paddle yourself while Captain Verma gives encouraging instructions from his loudspeaker.',
    isCovered: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    operatingArea: 'Gurugram Cyber City Highways',
    safetyEquipment: ['1x Life Jacket', 'Double-Bladed Carbon Paddle', 'GoPro Helmet Mount', 'Watertight Laptop Sleeve'],
    blockedDates: [],
    coordinates: { x: 25, y: 65 },
    captainName: 'Captain Verma',
    captainRating: 4.9,
    captainAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    status: 'active'
  }
];

export const FUN_SLOGANS = [
  "Your Uber is now a canoe.",
  "Traffic? What traffic?",
  "Now accepting puddles as highways.",
  "Estimated splash time: 4 minutes.",
  "India's #1 On-Demand Urban Water Mobility Platform.",
  "Heavy rains? Don't cry, just float on by!",
  "Row, row, row your commute, gently down the street!",
  "When life gives you monsoons, we give you captains."
];
